### PR TITLE
ArchivesSpaceClient: handle no note content

### PR DESCRIPTION
**Pull request by Hwesta**
`n['content'] = note['subnotes'][0]['content']` raises if `content` doesn't exist, which can apparently happen.  Added catch of KeyError to handle this.

### CODE REVIEW

**Comment by sevein** [comment]
I really like Python's syntax to handle multiple exceptions at once! :+1:

**Comment by mistydemeo** [comment]
:+1: Add a test for this?

**Comment by mistydemeo** [comment]
Ping re: test

**Comment by Hwesta** [comment]
Thanks for finding a testcase, Misty!

**Pull request merged**
